### ISSUE TITLE
Add TokenID to tokentx API endpoint

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#1046]
Token ID is missing for ERC721 tokens on the `tokentx` API endpoint. When a user queries a transaction that includes a token transfer for an ERC-721 token we should show the `tokenID` instead of the `value`.

**Comment by valeryvaskabovich** [comment]
Thanks @acravenho for bringing that up! I have a few more questions: what are your thoughts on returning tokenId from tokenbalance/tokenlist in case of ERC-721 instead of 0 value? Would it be possible to add token type (ERC-20/ERC-721) to the response from tokenlist? 
If you feel that my feature requests are feasible I can create issues in Github.
Thanks!

**Comment by acravenho** [comment]
@valeryvaskabovich Yes, those are all great requests. We're currently building out our GraphQL API endpoints. Do you have any interest in adding them there instead?

**Comment by valeryvaskabovich** [comment]
@acravenho Great! Is there any easy way to configure GraphQL for these requests (according to official GraphQL docs it looks super easy)? Since I'm not really familiar with Erlang and Elixir it will take some time to ramp up to get this done. Or should I just create issues in Github?

Thanks!
