### ISSUE TITLE
Improve Token Transfers listing performance

### ISSUE THREAD

**Issue by amandasposito** [poanetwork/blockscout#1053]
For some addresses in ETH Mainnet, it's not possible to open the `Token Transfers` tab that lists the token transfers info.

[0x9d8be94d0612170ce533ac4d7b43cc3cd91e5a1a](https://blockscout.com/eth/mainnet/tokens/0x9d8be94d0612170ce533ac4d7b43cc3cd91e5a1a/token_transfers)

### Environment

- Tested on BlockScout's Production Environment.

### Steps to reproduce

1. Visit: https://blockscout.com/eth/mainnet/tokens/0x9d8be94d0612170ce533ac4d7b43cc3cd91e5a1a/token_transfers
2. Click on the `Token Symbol` of certain tokens and it's very slow or doesn't load at all.

### Expected behavior

- Should see the `Token` information, including transfers.

### Actual behavior

- It keeps loading and, after some time, a `Gateway Timeout` message is shown.

**Comment by amandasposito** [comment]
This may be an intermittent problem, it doesn't happen all the time.

**Comment by fvictorio** [comment]
I've been looking at this but sadly I can't think of a better option than denormalizing: adding a `block_timestamp` column to the `token_transfers` table.

The slow query is the one that fetches the last 50 transfers for the given token address. This joins the token transfers with the blocks (through the transactions table), sorts the result by the block timestamp and then limits it to the first 50. But if the token has a lot of transfers, all of them will have to be fetched, joined and sorted before applying the limit. Plus, postgres sometimes thinks the best way of doing this is to do a full scan on the blocks table.

An alternative to denormalization is adding 2 indexes: one in the transactions table using the columns `(hash, block_hash)` and the other in the blocks table using the columns `(hash, timestamp)`. This allows postgres to use index only scans in the joined tables: the rows won't be fetched because the index has the necessary data. The performance of the query improves with this, but it may not be enough (a token with 200K transfers takes 10 seconds, for example) and I don't think it will scale.

**Comment by fvictorio** [comment]
In this case the column would be `block_timestamp`, but I guess that ordering by block number should give the same results.

**Comment by feliperenan** [comment]
@acravenho Could we order the list of token transfer on this page by the block_number? If so, we just need to add this column at token transfers table since the indexer already sends the block number to be imported by Token Transfer. Of course, we'll need to migrate the block number for the ones that already has been indexed, I think we can fetch it from the transactions table 🤔.

Also, would the `index` that you are talking about be the `log_index` in the token transfers table? If so, we don't need to denormalize this one.

https://github.com/poanetwork/blockscout/blob/c5fa7210b82b83930156367c52ca275d17412cba/apps/explorer/lib/explorer/chain/token_transfer.ex#L45
