### ISSUE TITLE
Implement Emission Reward tile

### ISSUE THREAD

**Issue by amandasposito** [poanetwork/blockscout#1149]
Related to #768

An `emission contract` is a value transfer that is paid for every block. 

In the POA Chains, there is a `smart contract` that every `block` sends one POA to an `address`. There is a defined `address` that comes from the `block_trace call` (in the `indexer` is called `beneficiaries`). 

It basically just updates the `balance` of one particular `address` or `multiple addresses` (defined in the `block_trace` call). If you look in the `block_trace` there is a `type` `reward` and there is one POA that is rewarded to a particular `address`.

We are currently tracking the balance of this value transfer by utilizing `block_trace` and calculating the balance for every address seen within the output.

When a new balance change is seen we should create a transaction card for this value transfer. This transaction card should have a unique color and be listed on the main transaction tab.

**This is not an item in the `transactions` table so the current listing does not support this information.**

### Questions? 

* Where would the count about the emissions be? Should this be done in a separate issue?
* Which color should be this new card?
* Which pages should display this card? (home, transactions or address transactions)

### Acceptance Criteria

* For every emission reward, it must be displayed a tile card with a different color from the previous tiles;
* The tile must contain the type of transaction (emission contract), status, `block` hash, the `address contract hash` in the `from`, the `to` `address hash`, the `value` rewarded and how long time ago it happened;
* This tile should not be displayed in others networks besides POA.

**Comment by acravenho** [comment]
related to #1121

**Comment by amandasposito** [comment]
@acravenho I updated this issue and left some questions when you have the time, could you take a look? thanks!

**Comment by acravenho** [comment]
@amandasposito 
1. I think this will be very difficult to do since we are not keeping the state of this action up to this point. Currently, we're only asking the `coin_balance_fetcher` to go check the address, the actual state of the value transfer is not being recorded anywhere. Without this, it would be difficult to keep a count. Let's move this to another issue.

2. #B38DC9

3. I believe this should go on the transactions and address transactions page. I'm open to your thoughts on this. I am 100% sure it should go on the address transactions page but unsure if it should be included on the transactions page.
