### ISSUE TITLE
Bug in verified read contract data.

### ISSUE THREAD

**Issue by bejavu** [poanetwork/blockscout#1202]
This issue is regarding a bug found in our fork of the explorer deployed for the Fuse (CLN) sidechain
([https://github.com/ColuLocalNetwork/CLNexplorer](https://github.com/ColuLocalNetwork/CLNexplorer))
After deploy and verify of some smart contract, the read contract tab showing incorrect data.

### Steps to reproduce
* Deploy the Centre (USDC) contracts (both implementation and proxy contracts)
* Verify both of them
* Go to the Proxy contract page and see the read contract tab.
* Example: [https://explorer.fuse.io/tokens/0x415c11223bca1324f470cf72eac3046ea1e755a3/read_contract](https://explorer.fuse.io/tokens/0x415c11223bca1324f470cf72eac3046ea1e755a3/read_contract)

### Expected behavior
* admin should refer to the account that deployed the contract.
* implementation should refer to the implementation contract.
* In the example above: implementation should be: 0xae4ed6504fc838535c82c3f1e1e4794e4c35efa5
and admin should be: 0xAde4785c5B5699E25B1E345d708be6295CDce938

### Actual behavior
* Both admin and implementation refer to some random hex.
* In the example above: 0x282d33323031352920564d20657865637574696f6e206572726f722e

**Comment by fvictorio** [comment]
@bejavu Just to be sure, are you referring to this contracts, right? https://github.com/centrehq/centre-tokens

**Comment by bejavu** [comment]
@fvictorio Yes.
To be more sure, this contract: https://github.com/centrehq/centre-tokens/blob/master/contracts/FiatTokenProxy.sol

**Comment by fvictorio** [comment]
Hey @bejavu. I think the problem is in the `admin` implementation:

```solidity
  function admin() external view ifAdmin returns (address) {
    return _admin();
  }
```

As you see, there's an `ifAdmin` modifier:

```solidity
  modifier ifAdmin() {
    if (msg.sender == _admin()) {
      _;
    } else {
      _fallback();
    }
  }
```

I guess it's done that way to allow using the proxy for contracts that have `admin` and `implementation` methods. So you have to call it from the admin address to get the proper response; otherwise, the call is proxied to the underlying contract. In this case, that's the token, and so it returns an error (because the token doesn't have `admin` or `implementation` methods).

The random hex, that is shown instead of indicating that there was an error, seems like a problem. But other than fixing that, I don't know what could be done here.

**Comment by bejavu** [comment]
Got it.
I guess that it that case, an revert error instead of a hex string sounds like a good solution. 
Thanks, I will open an issue about it in the centre repo.
Also I will try to reproduce it on ropsten to see how etherscan deals with it.

**Comment by bejavu** [comment]
BTW, etherscan returns null values in their read contract tab for the same contract:

https://ropsten.etherscan.io/address/0xff7d280bf5ba773e1254a1fbbcf13fcc2a29ec02#readContract

**Comment by acravenho** [comment]
@bejavu Do you think it's a better user experience to return `null` values?

**Comment by bejavu** [comment]
Its better than arandom hex, cleaner. 
Maybe a revert error will be better
