### ISSUE TITLE
Map ERC-20 tokens to price on CoinMarketCap API

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#1237]
### Motivation

Users want to see the USD price associated with the tokens they hold.

### Problem

We need to map the contract address of the ERC-20 token to the CoinMarketCap API price point. In order to do so, we need to use this list of ERC20 token contract addresses provided my MyEtherwallet and match them to the price points we receive from CMC

https://github.com/kvhnuke/etherwallet/blob/mercury/app/scripts/tokens/ethTokens.json

### Requirements

1. Display the USD price in the for each token in the token dropdown. 
2. Display the total USD price in the token overview section similar to how Etherscan displays the token USD prices
3. On the tokens tab, display the USD price for each token.

**Comment by fvictorio** [comment]
Some comments/questions about this:

- The CMC API allows fetching the price of a token using its symbol, not address (see [here](https://coinmarketcap.com/api/documentation/v1/#operation/getV1CryptocurrencyQuotesLatest)). You can also pass a list of symbols, but if one of those symbols is not recognized by CMC, the whole request will fail. This may limit our design options.
- Where will the list of "known" tokens live? It can be hardcoded, or fetched from some endpoint, or it can be a table in the DB. In my opinion, having a table for this seems like the best option, since it's easy to update at runtime.
- I guess we'll want to reduce the number of times we use the API. I think the best option here is some kind of cache with TTL. Do we have something like that in the project?

So far I'm assuming that we'll fetch the price for each token when we need it, but there are other options. For example, we could have a "price" column in the `tokens` table and update it regularly with the last price. Then we just show this value in the frontend.

**Comment by acravenho** [comment]
1. In order to solve the symbol/contract issue we need to utilize a trusted source to map the contract address to a symbol. This is the reason we will utilize https://github.com/kvhnuke/etherwallet/blob/mercury/app/scripts/tokens/ethTokens.json. 

2. I would suggest we use the :ETS table similar to what we're already using for the `coin price`. Here is how we're currently utilizing this table: https://github.com/poanetwork/blockscout/blob/master/apps/explorer/lib/explorer/exchange_rates/exchange_rates.ex

3. Please see here where we are already storing the coin price: https://github.com/poanetwork/blockscout/tree/master/apps/explorer/lib/explorer/market
