### ISSUE TITLE
After blocks syncronization counter of transactions doesn't match actual amount

### ISSUE THREAD

**Issue by APshenkin** [poanetwork/blockscout#1325]
After blocks syncronization our blockscout instance show that there is 294,025,088 transactions. Blockscout.com shows 373,553,376. Etherscan - 373303987.

Blockscout.com and Etherscan are close enough, but our instance of blockscout has missing 79 M transactions. Looks that something went wrong. What we can to do to fix this? 

Also after blocks syncronization other header appears: `Indexing Tokens - We're indexing this chain right now. Some of the counts may be inaccurate.`
What does it mean? For what this indexing is requiered? Can this indexing be disabled?

We are using geth without internal transactions

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
```
Erlang/OTP 21 [erts-10.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.7.3 (compiled with Erlang/OTP 21)
```

* Operating System:
```
Debian GNU/Linux 9 (stretch)
```

### Expected behaviour
Transaction counter are close enough to etherscan and Blockscout

### Actual behaviour
73M transactions difference. Indexing Tokens popup appears

**Comment by vbaranov** [comment]
Basically, there are 2 sources to update txs counter:
- if the cache is empty we display estimated value counter from Postgres system statistic table
- otherwise, txs counter displayed from the cache. The schedule to update the cache is configured with env variable. The related thread is here https://github.com/poanetwork/blockscout/issues/2195#issuecomment-503913346
