### ISSUE TITLE
Token Balances not in address_current_token_balance table

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#1345]
While comparing tokens between different explorers I started noticing a small number of tokens that weren't displaying in BlockScout. These token balances are present in the `address_token_balances` table but not in the `address_current_token_balances` table, therefore, they do not show up in the UI.

Here is an example:

* Contract Address: `0xcce629ba507d7256cce7d30628279a155c5309c5`
* Address: `0x9a4A90E2732F3Fa4087B0Bb4bF85c76d14833dF1`

**Comment by KronicDeth** [comment]
If this is on Eth Mainnet that pair does not have an `address_current_token_balances`:

```
ether=> SELECT * FROM address_current_token_balances WHERE token_contract_address_hash = '\xcce629ba507d7256cce7d30628279a155c5309c5' AND address_hash = '\x9a4A90E2732F3Fa4087B0Bb4bF85c76d14833dF1';
 id | address_hash | block_number | token_contract_address_hash | value | value_fetched_at | inserted_at | updated_at 
----+--------------+--------------+-----------------------------+-------+------------------+-------------+------------
(0 rows)
```

But it does have a `address_token_balances`:

```
ether=> SELECT * FROM address_token_balances WHERE token_contract_address_hash = '\xcce629ba507d7256cce7d30628279a155c5309c5' AND address_hash = '\x9a4A90E2732F3Fa4087B0Bb4bF85c76d14833dF1';
    id     |                address_hash                | block_number |        token_contract_address_hash         | value |      value_fetched_at      |        inserted_at         |         updated_at         
-----------+--------------------------------------------+--------------+--------------------------------------------+-------+----------------------------+----------------------------+----------------------------
 152935201 | \x9a4a90e2732f3fa4087b0bb4bf85c76d14833df1 |      6554644 | \xcce629ba507d7256cce7d30628279a155c5309c5 |  1000 | 2018-10-21 05:39:06.535695 | 2018-10-21 05:39:06.759996 | 2018-10-21 05:39:06.759996
(1 row)
```

`address_current_token_balances_in_batches.sql` can fix this type of fault because it is purposely using `UPDATE` to fix pre-existing `address_current_token_balances`.

`insert_address_current_token_balances_in_batches.sql` can `INSERT` new `address_current_token_balances`, but it would rewrite the whole of `address_current_token_balances`, so you can't use it.

So either a previous bug that was fixed or a current bug is allowing `address_token_balances` to be written without `address_current_token_balances` being upserted.

**Comment by acravenho** [comment]
Yes, it looks like it was a bug from a few months ago. It sounds like we'll need a new script to fix these tokens. It's most likely a very small percentage that are not in the `address_current_token_balances` table.

**Comment by KronicDeth** [comment]
I'm going to run locally against Mainnet for a bit to confirm the bug isn't still present.

**Comment by KronicDeth** [comment]
This query shows a non-zero (`33039`) count when I run locally, so I think whatever is doing it is still present:

```
SELECT COUNT(*)
FROM (
       SELECT DISTINCT token_contract_address_hash,
                       address_hash
       FROM address_token_balances
            EXCEPT
       SELECT token_contract_address_hash,
              address_hash
       FROM address_current_token_balances
     ) AS t
```

The count does vary though as I let the indexer run in the background, so something is sometimes filling in the value.

**Comment by KronicDeth** [comment]
`address_current_token_balances` is passed to `Explorer.Chain.import` in 2 places:

1. `Indexer.Block.Realtime.Fetcher.import/2`
  https://github.com/poanetwork/blockscout/blob/0c1e18452e5d8b63317a34b25f6299b4880db4ff/apps/indexer/lib/indexer/block/realtime/fetcher.ex#L181-L191
2. `Indexer.TokenBalance.Fetcher`
    https://github.com/poanetwork/blockscout/blob/6165f6757ff76c59707a4fc47e17533846bf7463/apps/indexer/lib/indexer/token_balance/fetcher.ex#L80-L86   
https://github.com/poanetwork/blockscout/blob/6165f6757ff76c59707a4fc47e17533846bf7463/apps/indexer/lib/indexer/token_balance/fetcher.ex#L105-L115

This means that the `Indexer.Block.Catchup.Fetcher` was previously expected *NOT* to fill in `address_current_token_balances` and for them to only exist once `Indexer.TokenBalance.Fetcher` found their value.

So me seeing that some were not filled in is because my local `Indexer.TokenBalance.Fetcher` was still catching up to `Indexer.Block.Catchup.Fetcher`.

However, this does mean that https://github.com/poanetwork/blockscout/issues/1345#issuecomment-454926159 still should not happen because `Indexer.Block.Catchup.Fetcher` does not know the `value` for `address_token_balances`, so the row in `address_token_balances` can only be created by `Indexer.Block.Realtime.Fetcher` or `Indexer.TokenBalance.Fetcher` which would also fill in the `address_current_token_balances`.
