### ISSUE TITLE
Update Bridged token supply when wrapped token is transferred.

### ISSUE THREAD

**Issue by LiorRabin** [poanetwork/blockscout#1354]
This issue is regarding a bug found in our fork of the explorer deployed for the Fuse (CLN) sidechain
(https://github.com/ColuLocalNetwork/blockscout)

The total supply of a token is incorrect and as a result the percentage of tokens held by the holders is incorrect as well.

### Steps to reproduce

https://explorer.fuse.io/tokens/0xacc4ecacec9f5284cbf7997625bec7d69ff662c8/token_holders

### Expected behaviour

Total supply should be the total amount of tokens the holders hold.

### Actual behaviour

Total supply amount is wrong

**Comment by acravenho** [comment]
Hi @LiorRabin,

I don't think there is a bug here in the code. To simply count token holders is not scalable for larger EVM chains. There could be improvements specifically for bridged/wrapped tokens to check the supply when a particular hash is seen. We currently do this on xDai Chain in order to keep track of the total market cap. 

In the meantime, you can have the explorer check the total token supply of the contract more frequently by adjusting this configuration setting: https://github.com/poanetwork/blockscout/blob/3e19a8afab91195978e2e2a4a958927aabc0e5dc/apps/indexer/config/config.exs#L10

**Comment by LiorRabin** [comment]
@acravenho thank you, I understand
