### ISSUE TITLE
Transaction logs not working

### ISSUE THREAD

**Issue by LiorRabin** [poanetwork/blockscout#1355]
This issue is regarding a bug found in our fork of the explorer deployed for the Fuse (CLN) sidechain
(https://github.com/ColuLocalNetwork/blockscout)

When trying to see logs of a transaction, `Internal server error` is received.

### Steps to reproduce

* Go to any transaction with internal transactions, for example: https://explorer.fuse.io/tx/0x71291740c25e11018d7a283ca520034199384d8f0a8a54c842b8467a60973129/internal_transactions
* Go to "Logs" https://explorer.fuse.io/tx/0x71291740c25e11018d7a283ca520034199384d8f0a8a54c842b8467a60973129/logs

### Expected behaviour

See the transaction logs in a form similar to what can be seen on etherscan.

### Actual behaviour

Internal server error is received.

**Comment by acravenho** [comment]
Hey @LiorRabin,

I'm not able to replicate the issue with logs. I believe it is due to your explorer being very far behind `master`.  I can tell your static files haven't been updated in months on the deployed version. Here is what a verified contract should look like:

![verifiedfuse](https://user-images.githubusercontent.com/17620007/51257754-571f1180-1976-11e9-87c5-41bd72fedf40.png)

I verified the contract located here: `0x1892804aede280db4041605749dce04e5df69344` and was able to view all logs associated with the address.

Please update your explorer's build. Let me know if you're having issues.

**Comment by LiorRabin** [comment]
Hello @acravenho and thanks for the quick reply.
We will update our code and re-check this.
I will let you know if it was resolved.

**Comment by acravenho** [comment]
Please let me know if you are having any further issues.
