### ISSUE TITLE
Internal tx doesn't parse if tx data is  `0x0`

### ISSUE THREAD

**Issue by mnugumanova** [poanetwork/blockscout#1427]
I made my first solidity contract today on POA and I wanted to tell you about my experience with blockscout.

if I make a contract call, the explorer automatically sees all internal tx and calculates correct balance
but if I make a call to fallback which will make the same function call, it doesn't see internal transactions at all and it doesn't show a correct balance of recipients. 
Example: 
https://blockscout.com/poa/core/tx/0xe92aa379d0cfc11499b9e2841195083ebf9b72c0a3ae9c42f9921d476647166f/internal_transactions
Notice that there is no data for that fn call, but it actually calls a fn inside the fallback

same exact call but through a method signature:
https://blockscout.com/poa/core/tx/0x9f384da398a8756ec07a5cd89efaaaef10b3558f20285593c166f69bdf248617/internal_transactions

also if I call `eth_getBalance` it does show correct balance vs blockscout balance after such fallback transaction.

I think there is some issue if tx has 0x data, the explorer doesn't account that it could be a fallback call which will have internal transfers.

**Comment by acravenho** [comment]
Hi Mira,

Thank you for the feedback. Previously we would have handled fallback functions for contracts but recently we've changed the way we handle internal transactions in order to get Ethereum Mainnet indexed. This process stopped fetching internal transactions on transactions that were not sending data. We'll have to go back to drawing board and rethink this process once again to better detect these outlier cases for fallback functions.

**Comment by acravenho** [comment]
## Current Internal Transaction Rules
In order to process transactions at a faster speed, we designed a set of rules to eliminate the need to fetch internal transactions on all transactions

* Fetch internal transactions on any error
* Do not fetch internal transactions with no input
* Do not fetch internal transactions that contain an input of `a9059cbb`

## Changes needed
1. We will eliminate the rule above for not fetching internal transactions on no input but only if the transactions are interacting with a contract.
