### ISSUE TITLE
BlockScout Version environment variable not working

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#1468]
The `BLOCKSCOUT_VERSION` environment variable is not working currently. We tried to have it compiled previously in order to have to look the version up with every page load but this is broken.

**Comment by zachdaniel** [comment]
How is the BLOCKSCOUT_VERSION environment being set currently? Is it set when building a docker image? If it is set, and then `mix compile` is run, that may not be enough because the module in question `BlockScoutWeb` may not recompile. You may need to `mix compile --force`. Although that wouldn't be very fun because it would have to recompile the entire application. I could set it up such that it just checks once and stores the state in system env, that way we get the intended optimization but don't have to use the variable at compile time. Would you prefer that?

**Comment by acravenho** [comment]
Our deployment is through Terraform, https://github.com/poanetwork/blockscout-terraform. I feel that this should be very similar to how we handle `network` and `subnetwork`. I think it's very confusing for an end user to have to go through many extra steps to add an environment variable for the blockscout_version than it is to add a network, subnetwork, logo, and many more endpoints.

I feel this should be easily configurable here: https://github.com/poanetwork/blockscout/blob/master/apps/block_scout_web/config/config.exs

**Comment by zachdaniel** [comment]
I'll update it to work in the same way :+1:
