### ISSUE TITLE
Allow configuring a different node for the realtime fetcher

### ISSUE THREAD

**Issue by zachdaniel** [poanetwork/blockscout#1566]
In order to give the realtime fetcher a dedicated node, we need to be able to configure a separate set of connection info for just the realtime fetcher. If one is not configured, then we should use the current configuration.

The motivation for this is to make it such that the catchup fetcher and realtime fetcher don't step on eachother's toes. We don't want catchup fetcher congestion to slow down the realtime fetcher.

**Comment by goodsoft** [comment]
For the record, the actual motivation is to make sure the realtime fetcher only makes requests about recently added blocks to the node it gets websocket notifications from.
Otherwise, the load balancer routes some of the fetch requests to other nodes, which may be less up-to-date, and causes the realtime fetcher to abandon the block entirely and leave it to catchup fetcher.

**Comment by zachdaniel** [comment]
Good to know! I thought it was a performance issue :)
