### ISSUE TITLE
BlockScount against ethereum-PoA (clique)

### ISSUE THREAD

**Issue by NEO2756** [poanetwork/blockscout#1659]
I am trying to run Blockscout against EThereum-PoA (clique) private chain. Is it possible?

1. I tried to run using VARIANT==geth and I can see the transactions and Blocks, but Instead of Validotors/Signers/Sealers it shows "Miner" and all miner addresses are 0x000... as described in #1548 . 
2. How to change conversion unit from POA to ETH. (Any configurations?)

### Environment
* Elixir & Erlang/OTP versions (`elixir -version`):
Erlang/OTP 21 [erts-10.3.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.8.1 (compiled with Erlang/OTP 21)
* Operating System:
OSX

### Expected behaviour
Miner addresses should not be Zero.
Validators address should be shown. (just like https://blockscout.com/eth/kovan)

### Actual behaviour
Miner Address is all zeos. 0x000...
Miner should be validators/Sealers/Signers ?

**Comment by vbaranov** [comment]
Yes, it is possible. It is configurable here:
poanetwork/blockscout/blob/12aa15671142af00b35ff05aeac107c2c686c4c8/apps/block_scout_web/priv/gettext/default.pot

Please check the related post https://forum.poa.network/t/deployment-differences-between-each-blockscout-chain/1950

**Comment by NEO2756** [comment]
Thanks a ton @vbaranov , it helps.

**Comment by lightninggalaxy** [comment]
I am having the same issue on my private chain. I'd like to be able to show validator/signer addresses instead of mined by 0x000. I have checked https://forum.poa.network/t/deployment-differences-between-each-blockscout-chain/1950 but it seems that the first file doesn't have the line number indicated? The one that says Update Validated/Validator to Mined/Miner or Signed/Signer. Please advise what I must change in order to see the validator/signer addresses instead of mined by 0x000. Thanks!
