### ISSUE TITLE
UI changes for "New Smart Contract" page

### ISSUE THREAD

**Issue by pashagonchar** [poanetwork/blockscout#1726]
Zeplin:
https://zpl.io/bzq8QMz
https://zpl.io/VOx04k1

Invision
https://invis.io/G7RGUWGYD2M
Please replace text where "lorem ipsum"
--------------------------------
![poa_new_smart_contract_1_2](https://user-images.githubusercontent.com/16716926/55867159-a007f000-5b8a-11e9-8ed5-021cb09c18ab.png)
![poa_new_smart_contract_2_2](https://user-images.githubusercontent.com/16716926/55867167-a4cca400-5b8a-11e9-95d6-6f5a0450fd30.png)

**Comment by igorbarinov** [comment]
@andogro please provide us tooltips for the field

**Comment by andogro** [comment]
Here is v1 of tooltips, let me know if any are too long and I will try to shorten.  The bold on left is the field value, following is the tooltip text for the right hand side. 

_Question: For #5, if Optimization is checked, will we need to collect the # of optimization runs or has this been deprecated?_

**New Smart Contract Verification** (add Verification)

1. **Contract Address:** The 0x address supplied on contract creation.
2. **Contract Name:** Must match the name specified in the code. For example, in `contract MyContract {..}` **MyContract** is the contract name. 
3. **Compiler:** The compiler version is specified in `pragma solidity X.X.X`. Use the compiler version rather than the nightly build. If using the Solidity compiler, run `solc —version` to check.
4. **EVM Version** (currently missing ‘r’):  The EVM version the contract is written for. If the bytecode does not match the version, we try to verify using the latest EVM version. [EVM version details](https://ethereum.stackexchange.com/questions/13014/please-provide-a-summary-of-the-ethereum-hard-forks).
5. **Optimization:** If you enabled optimization during compilation, select yes. 
6. **Enter the Solidity Contract Code** (delete below, since it is to the side): We recommend using flattened code. This is necessary if your code utilizes a library or inherits dependencies. Use the [POA solidity flattener](https://github.com/poanetwork/solidity-flattener) or the [truffle flattener](https://www.npmjs.com/package/truffle-flattener).
7. **ABI-encoded Constructor Arguments (if required by the contract):** Add arguments in  [ABI hex encoded form](https://solidity.readthedocs.io/en/develop/abi-spec.html). Constructor arguments are written right to left, and will be found at the end of the input created bytecode. They may also be [parsed here](https://abi.hashex.org/).  

**Contract Libraries (if used by the contract)**

**Library name:** A library name called in the .sol file. Multiple libraries (up to 5) may be added for each contract. Click the Add Library button to add an additional one.

**Library Address:** The 0x library address. This can be found in the generated json file or Truffle output (if using truffle).

**Comment by gabitoesmiapodo** [comment]
@vbaranov @andogro 

Is this a new section?

If it isn't, how can I get there?

**Comment by andogro** [comment]
@gabitoesmiapodo here is an example on the sokol network:
https://blockscout.com/poa/sokol/address/0x4d45578b70a4a1b850f4519d5a16b89f6f50699a/contract_verifications/new

This page is reached when a new smart contract is created and needs to be verified. In this example, the contract details are here: https://blockscout.com/poa/sokol/address/0x4d45578b70a4a1b850f4519d5a16b89f6f50699a/transactions

When you click on the `code` tab, you will see the ABI contract creation code and a button to verify and publish. When you click this button, you are taken the to section above to verify the contract.

**Comment by gabitoesmiapodo** [comment]
@andogro 

Thank you, I'll look into it.
