### ISSUE TITLE
`txlistinternal` is timing out on some addresses

### ISSUE THREAD

**Issue by zachdaniel** [poanetwork/blockscout#2076]
`txlistinternal` is timing out on some addresses

`/api?module=account&action=txlistinternal&address=0x1B3858E01CCE5d0491f3c96A9996a65607f3493b&offset=10` is responding with a 504.

### Environment

* Mainnet production

### Steps to reproduce

* Make this request `/api?module=account&action=txlistinternal&address=0x1B3858E01CCE5d0491f3c96A9996a65607f3493b&offset=10`

**Comment by krijnsent** [comment]
@zachdaniel I can confirm this issue. My (noobly) expected behaviour of txlistinternal is the same as txlist and tokentx : only have an address as the parameter and give back a list of transactions. The txlist and tokentx work like a charm, the txlistinternal times out with a 504 (same address as parameter).
