### ISSUE TITLE
block_transactions_mismatch repeatedly in logs

### ISSUE THREAD

**Issue by dwalintukan** [poanetwork/blockscout#2234]
I keep getting this log over and over again. Is this an issue and will this resolve itself over time?

```
2019-06-24T15:07:37.161 application=indexer fetcher=blocks_transactions_mismatch [info] BufferedTask #PID<0.11260.14> (Indexer.Temporary.BlocksTransactionsMismatch) ran out of work, but work queue was shrunk to save memory, so restoring lost work from `c:init/2`.
```

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): 1.8.2
* Operating System: Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-1032-aws x86_64)

### Steps to reproduce

Can't push this code up sorry. It's a private repo.

### Expected behaviour

Not to show that log over and over again.

### Actual behaviour

Showing that error constantly. The blocks are syncing and everything seems to be working, but the logs are crowded with that message.

**Comment by pasqu4le** [comment]
Hey @dwalintukan, the recurring log is due to the fetcher being repeatedly asked to shrink its queue.

I checked and artificially reproduced the problem and what happens is that basically at initialization `BlocksTransactionsMismatch` will load from the database **all** the blocks that need to be processed.
After it starts processing the memory limit is hit and it is likely that this fetcher is on the top of the list for being memory consuming, so it gets asked to shrink, cutting down the queue of by half, several times.
What happens is that when what remains of the queue gets processed, knowing it has been shrunk before, it will ask the database all the blocks that still need to be dealt with, but they are still too many for the memory limit and the loop starts again.

This cycle will eventually stop after enough blocks have being updated and the fetcher still does its job and terminates correctly.

There is no good way to prevent this issue from the beginning without severely impacting the performance for those that do not hit the limit, however the memory footprint of the fetcher can be largely reduced and that't what #2258 does, so that this issue is much more unlikely to arise.

**Comment by dwalintukan** [comment]
@pasqu4le Great explanation, thanks for letting me know.
