### ISSUE TITLE
Upgrade to V2 of CoinMarketCap API

### ISSUE THREAD

**Issue by alexgaribay** [poanetwork/blockscout#234]
Currently, fetching exchange rates for tokens use V1 of CoinMarketCap's API. V1 will be deprecated on Nov 30, 2018. The current code should be upgraded to use V2 of the API to avoid any downtime.

See https://coinmarketcap.com/api/#endpoint_ticker for API documentation.

**Comment by tmlee** [comment]
@alexgaribay you may consider looking and using our API at https://www.coingecko.com/api/docs/v3
straight forward to consume, no api keys needed, and abundance of data to choose from
let me know what you think, happy to answer any questions

**Comment by Lokraan** [comment]
@tmlee is there a way to get the market data for a coin with it's `current_price` in reference to multiple currencies?

IE instead of `https://api.coingecko.com/api/v3/coins/markets?vs_currency=btc` where you can only get the prices in reference to one currency you could do `https://api.coingecko.com/api/v3/coins/markets?vs_currency=btc&vs_currrency=usd` to get `current_price_btc` and `current_price_usd`.

As far as I know the current solution to this is getting the price of btc currently, then dividing the current price in usd of the other currencies by the btc price.

**Comment by tmlee** [comment]
@Lokraan at the current setup, you can get the price in multiple currencies with the following 2 endpoints (for example)

1. https://api.coingecko.com/api/v3/coins
2. https://api.coingecko.com/api/v3/coins/bitcoin

The disadvantage of (1) is that you get all coins, but you will need to do some pagination
The disadvantage of (2) is that you will have to make 1 query per coin

Your suggestion on adding more currencies seem reasonable, but do also let me know if the above 2 endpoints can solve the issues you are facing

**Comment by Lokraan** [comment]
@tmlee the solution I'm using is to get the current price in bitcoin with `/exchange_rates` and then use `/coins/markets?vs_currency=usd` and manually calculate the price in bitcoin. 

The benefits of this is that I don't need to query more than two times to get all of the data.

I was wondering if you guys would be interested in having a graphql api that allows users to specify exactly which coin data they want. For example I didn't find it useful to have the description of bitcoin when I just wanted the price of it.

If you guys are interested I would be more than willing to help assist in implementing it. I don't have any past experience with Ruby, but Elixir is fairly similar and I have built servers that have utilized graphql in Elixir and NodeJS.

**Comment by acravenho** [comment]
Updated in #1278
