### ISSUE TITLE
Draw inline error messages instead of modals for staking dialogs

### ISSUE THREAD

**Issue by goodsoft** [poanetwork/blockscout#2500]
Consider this modal window: https://projects.invisionapp.com/share/YPQNPDTW4ZB#/screens/349758673
Currently, errors in staking dialogs are displayed using error modal windows: https://projects.invisionapp.com/share/YPQNPDTW4ZB#/screens/349758831

This approach has several problems:
1. Separate modal window makes user lose their context, i.e. you don't see, which value exactly caused the error.
2. It is even worse if several errors occured — we either show only one of the errors, or show a list of errors, which the user won't even be able to remember when getting back to the form.
3. Due to the way modal windows are implemented, it's too much effort to properly bring back the original modal window after error modal window is closed.

Instead I suggest displaying errors in the form itself by highlighting inputs with invalid values and showing error messages nearby.

Error modal windows will still be used in cases no further user action is required/possible, i.e. nothing would happen after the error window is closed.

**Comment by pashagonchar** [comment]
@goodsoft 

zeplin: https://zpl.io/ag63Kg0

<img width="1280" alt="validaors_become_candidate_error" src="https://user-images.githubusercontent.com/16716926/62954378-f8c8ed00-bdf7-11e9-8120-8123392b23e5.png">

**Comment by varasev** [comment]
@pashagonchar I think we also need to have an ability to display another type of errors (right in the window) which are not related to input fields. For example, that could be some error in a transaction or something like that. Maybe we just need to fade out the window content and display an error above the content (with OK button) in a separate DIV layer inside the window (so that we wouldn't close the window to show an error); when a user clicks on OK, the error text disappears and the window content is visible again.

**Comment by pashagonchar** [comment]
@varasev do you mean something like this ?

![validaors_become_candidate_error_2](https://user-images.githubusercontent.com/16716926/63020320-78ad9080-bea6-11e9-9e76-732e5833d728.png)

**Comment by varasev** [comment]
@pashagonchar Yes, looks good, thanks

**Comment by goodsoft** [comment]
@maxgrapps may I ask you to add HTML markup and CSS for these errors as a PR based on `staking` branch? You can put any scaffolding for testing, I'll take over from there to make them actually work.
