### ISSUE TITLE
eth_block_number returns old block on Ethereum Mainnet

### ISSUE THREAD

**Issue by akolotov** [poanetwork/blockscout#2583]
I have tried to use `https://blockscout.com/eth/mainnet/api?module=block&action=eth_block_number` to get the latest block number. But it always returns `0x7ece30`.

![image](https://user-images.githubusercontent.com/20793260/63127344-c9aea900-bfba-11e9-8069-e92480080e2f.png)

**Comment by vbaranov** [comment]
@akolotov sorry about that. The issue is due to the splitting of web application and API servers. Some API endpoints get the data from ETS cache. And cache due to the lack of architecture design doesn't update on the API server side for now. As a workaround, I switched `eth_block_number` API to get the data from the application server where the cache is updating. Thus, for now, that endpoint returns correct latest block. I will keep this issue open until we will implement cache update on API server side.
