### ISSUE TITLE
Contract address not showing code tab

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#263]
This address `0x1c494fa496f1cfd918b5ff190835af3aaf60987e` is a contract but it is not showing the code tab. 

<img width="635" alt="screen shot 2018-06-07 at 7 38 17 pm" src="https://user-images.githubusercontent.com/17620007/41131576-5f1bb26c-6a8a-11e8-88b2-955e689aaef0.png">

Here is the same address on sokol explorer: https://sokol.poaexplorer.com/address/search/0x1c494fa496f1cfd918b5ff190835af3aaf60987e

**Comment by gfreh** [comment]
@amandasposito and @acravenho I've tested it on localhost and everything seems to be right! I've moved it to `Ready for acceptance`.

**Comment by acravenho** [comment]
I'll test soon and provide feedback here soon after.

**Comment by acravenho** [comment]
LGTM!

**Comment by melnikaite** [comment]
I'm afraid the issue should be reopened, it doesn't work in my environment

### Environment

* Operating System: OS X 10.14
* Docker 18
* Ganache CLI v6.2.5 (ganache-core: 2.3.3)

### Steps to reproduce

* ganache-cli -v -i 4447 -l='0x7A1200' -g='0x01'
* deploy any contract
* git clone git@github.com:poanetwork/blockscout.git
* cd blockscout/docker
* COIN=ETH ETHEREUM_JSONRPC_VARIANT=ganache ETHEREUM_JSONRPC_HTTP_URL=http://host.docker.internal:8545 ETHEREUM_JSONRPC_WEB_SOCKET_URL=ws://host.docker.internal:8545 make start
* open contract address in blockscout ui


### Expected behaviour

Code tab is visible

### Actual behaviour

Code tab is not visible

**Comment by igorbarinov** [comment]
we have the same problem for POA Bridge multisig on Mainnet
https://blockscout.com/eth/mainnet/address/0x68445b9e334374435b26ff75f4236b8a152ab9a6/transactions
The code tab is not visible

for the same contract with _the same address_ it is visible on POA Core
https://blockscout.com/poa/core/address/0x68445b9e334374435b26ff75f4236b8a152ab9a6/contracts

Also, it is visible on mainnet
https://etherscan.io/address/0x68445b9e334374435b26ff75f4236b8a152ab9a6#code

**Comment by acravenho** [comment]
@melnikaite We do not support internal transactions on Ganache due to the fact that Ganache does not support internal transactions and does not plan to support them. 

@igorbarinov The reason that contract is not showing up yet is because that contract creation internal transaction has not been indexed yet. There is no bug here but just needs more time to get indexed.

**Comment by melnikaite** [comment]
What rpc method return internal transactions? Why they are required? Having code on address should be enough.

**Comment by acravenho** [comment]
Ganache uses a modified Geth implementation which uses `call_trace` on `debug_traceTransaction`. This is currently not supported by Ganache. We requested this support from them but they told us this was not a priority. 

A solution to this issue would be to use `eth_getCode` during indexing which is a quick call to make in order to receive the contract creation code. Closing this issue in favor of #1336
