### ISSUE TITLE
Different buttons colors

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#2641]
https://blockscout.com/eth/kovan/address/0x0000000000001b84b1cb32787b0d64758d019317/contracts

![screencapture-blockscout-eth-kovan-address-0x00000](https://user-images.githubusercontent.com/4341812/63847510-98f54900-c996-11e9-83c1-3235e01eb685.png)

**Comment by pashagonchar** [comment]
@vbaranov  correct color for button is #1f857e

**Comment by YegorSan** [comment]
@vbaranov 
Hi. I am sorry for disturbing. I have one important question. I would like to render on localhost verified contract somehow, or if it's possible to verify one of the contracts in order to get an appropriate view of a contract address page. I've tried but got the following message in server console : 

_application=que [info] [Que] Failed Job # 4 with Explorer.SmartContract.PublisherWorker_

I am actually can change everything without rendering it at all, but for testing purposes I am sure it's much better to have an ability to see the performed changes on my local server. Thank you in advance.

**Comment by vbaranov** [comment]
@YegorSan use Sokol chain locally to deploy and verify smart-contract:

- Sokol resources to connect to Sokol chain: https://forum.poa.network/t/sokol-testnet-resources/1776
- Sokol faucet to get free coins: https://faucet.poa.network/
- [Remix IDE](https://remix.ethereum.org/#optimize=false&evmVersion=null) + [Nifty Wallet Chrome extension](https://chrome.google.com/webstore/detail/nifty-wallet/jbdaocneiiinmjbjlgalhcelgbejmnid): to deploy your contract

and verify it with your local BlockScout instance

**Comment by YegorSan** [comment]
@vbaranov 

Thank's a lot for your help.

**Comment by YegorSan** [comment]
@vbaranov 
This issue was already fixed in #2637 PR which was already merged. If it's possible please re-check. Thank's in advance.
