### ISSUE TITLE
Stuck uncle height label and value

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#2681]
https://blockscout.com/eth/mainnet/blocks/0x8e19d3155593999710ba69e43f877e6e6472397c27a3bad73403a86bd5bfc667/transactions

![Screenshot 2019-09-09 at 11 24 18](https://user-images.githubusercontent.com/4341812/64515058-895df480-d2f4-11e9-95c5-874fe080d4ff.png)

**Comment by YegorSan** [comment]
@vbaranov  Hello Victor, I am sorry for such a question, but could you please explain me how can I render locally Uncle Details page. I may be wrong, but  actually, I am almost sure that this issue is related to the generated internationalization text and can be fixed from backend side by simply adding a small extra space there in default.pot file after double-dots  : 
![Screenshot (1)](https://user-images.githubusercontent.com/10085945/64592314-6135ca80-d3b4-11e9-934c-91fe0ef5e2a8.png)

Could you please check , and let me know if issue is not fixed. Thank you in advance.
