### ISSUE TITLE
Please enable CORS on xDAI API

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/blockscout#2722]
![image](https://user-images.githubusercontent.com/9360827/65393925-5f68f100-dd3c-11e9-935d-2de1cc139c71.png)

![image](https://user-images.githubusercontent.com/9360827/65393926-6859c280-dd3c-11e9-8b9b-72c553389d3f.png)

**Comment by phahulin** [comment]
The problem seems to be caused by redirect from `/poa/dai` to `/poa/xdai`. For some reason CORS headers are not sent in redirect response.
I added them manually, please check if it works for you now? For me it worked in incognito window, but didn't work in the main browser window, maybe cache or smth.

**Comment by rstormsf** [comment]
fixed! thanks. 
I changed `dai` to `xdai` url
