### ISSUE TITLE
Contract cannot be verified

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#2922]
The contract cannot be verified with parameters from Etherscan:

https://kovan.etherscan.io/address/0x39c2c88d22cf30cf1338c024ea428a368fcccaef#code

**Comment by ayrat555** [comment]
it's related to https://github.com/poanetwork/blockscout/issues/2392

**Comment by iFA88** [comment]
The issue is still available for a simple contract which deployed to the ETC blockchain:
https://blockscout.com/etc/mainnet/address/0xae42cf9974fd6585a33eaf4cc5955ae894d74047/contracts
During verification i'm redirected to https://blockscout.com/etc/mainnet/verify_smart_contract/contract_verifications and got 404 error.

**Comment by vbaranov** [comment]
@iFA88 if it is not related to `ABIEncoderV2` feature I would suggest to open a separate issue and please share the metadata of a contract so we will be able to test verification.

**Comment by vbaranov** [comment]
Verification of contracts with `ABIEncoderV2` is supported for contracts compiled with Solidity 0.6.0+ where this feature is not considered as experimental anymore
