### ISSUE TITLE
Heavy load for ERC-721 tokens data fetch

### ISSUE THREAD

**Issue by APshenkin** [poanetwork/blockscout#3056]
After some time when launching blockscout we can see a lot of logs (millions!) like

```
2020-03-15T19:24:13.430 application=indexer [warn] BufferedTask #PID<0.896.0> (Indexer.Fetcher.TokenInstance) bound queue is at maximum size (1) and 1 entries could not be added.
```
It seems that this cause our ETH archive node degradation. 

We have only one archive node for blockscout.

Maybe it's caused by low CPU/RAM ? What is the requirements for blockscout and how much ETH nodes do we need?

Also it's possible to disable ERC-721 tokens info fetch to reduce load for ETH node?

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.9.0 (compiled with Erlang/OTP 22)
* Operating System: Alpine Linux 3.10.0
* Blockscout Version/branch: 3.1.0-beta

### Steps to reproduce
Launch blockscout for mainnet and wait some time (in our case 5 hours)

### Expected behaviour
Normal explorer work without heavy loading

### Actual behaviour
services degradation

**Comment by vbaranov** [comment]
@APshenkin you can disable token instances metadata fetcher in indexer config by adding `config :indexer, Indexer.Fetcher.TokenInstance.Supervisor, disabled?: true` like this: https://github.com/poanetwork/blockscout/blob/68c47a0e03eeebfd561f94fa113f8049883890a3/apps/indexer/config/config.exs#L43

A single ETH node is fine for Blockscout. However, for Mainnet it should be quite beefy. Take a look to https://github.com/poanetwork/blockscout/issues/2013#issuecomment-495189456 comment for CPU, cores viable parameters for Mainnet.

**Comment by vbaranov** [comment]
@APshenkin 

Disabling of the token instances metadata fetcher is available as I commented above https://github.com/poanetwork/blockscout/issues/3056#issuecomment-600204621

Also, configuring batch size and concurrency for the token instances metadata fetcher is possible:
https://github.com/poanetwork/blockscout/blob/923bc75dcaeb3c4b771b85253c96d4d4569027d8/apps/indexer/lib/indexer/fetcher/token_instance.ex#L19-L20

In addition, I added processing of the metatada if the image URL is returned instead of token URI https://github.com/poanetwork/blockscout/pull/3128. Not sure if it affects your instance, though.

I am closing this for now.
