### ISSUE TITLE
Write Contract tab has some unnamed function

### ISSUE THREAD

**Issue by varasev** [poanetwork/blockscout#3413]
For example, this page: https://blockscout.com/poa/xdai/address/0xD218aA7619900da0ff5a04C6bBC3411D76d7F6c9/write-contract

Is it a field for a fallback function, or a bug?

<img src="https://user-images.githubusercontent.com/33550681/97665197-e7ffa800-1a8b-11eb-886f-87cb3a8151e7.png" width="400" />

**Comment by vbaranov** [comment]
@varasev It is not a bug. Fallback functions are enabled in *Write contract* feature.

Here is the piece of code where contract's writable functions are filtered in order to display them at *Write contract* or *Write proxy* tab:

https://github.com/poanetwork/blockscout/blob/8cdef0ba28f97d64a069b88923716214dd2ec3da/apps/block_scout_web/lib/block_scout_web/views/smart_contract_view.ex#L11-L13

**Comment by varasev** [comment]
Got it, thanks
