### ISSUE TITLE
Contract Verification API not working

### ISSUE THREAD

**Issue by olivdb** [poanetwork/blockscout#3474]
I'd like to automate the contract verification process on Sokol. I deployed [a basic example contract](https://blockscout.com/poa/sokol/address/0x07D596186f18888a6aB6E7e6e88C257207B18b8b/contracts) which I'm trying to verify using the API but I keep getting a `504 Gateway Time-out`. Manual verification using the same parameters works fine.

#### Contract code:
```
pragma solidity ^0.7.5; contract BasicContract { uint public x; function setX(uint _x) external { x = _x + 3; }}
```

#### Request:
```
curl -X POST --data 'module=contract&action=verify&addressHash=0x07D596186f18888a6aB6E7e6e88C257207B18b8b&name=BasicContract&compilerVersion=latest&optimization=false&contractSourceCode="pragma solidity ^0.7.5; contract BasicContract { uint public x; function setX(uint _x) external { x = _x + 3; }}"' https://blockscout.com/poa/sokol/api 
```

#### Response:
```
<html><script src="/cdn-cgi/apps/head/UiiDYKjZgUH47bEce5l1HQMn91A.js"></script><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
```

Is the API opened for usage outside Blockscout web UI?

**Comment by vbaranov** [comment]
@olivdb, yes, `/verify` API endpoint is publicly available. I found nothing wrong with your request. I was able to verify that contract with a multi-line variant of that command (see below). Probably, it was a temporary request timeout during your try. One hint I'd like to mention regarding verification of contracts: if use explicit compiler version, verification should be a little bit faster since Blockscout should not look up for the `latest` version of the compiler.

```
curl -d '{"addressHash":"0x07D596186f18888a6aB6E7e6e88C257207B18b8b","compilerVersion":"latest", "contractSourceCode":"pragma solidity ^0.7.5;

contract BasicContract {
    uint public x;
    function setX(uint _x) external {
        x = _x + 3;
    }
}
","name":"BasicContract","optimization":false}' -H "Content-Type: application/json" -X POST "https://blockscout.com/poa/sokol/api?module=contract&action=verify"
```

Please, let me know if you still experience the issue with automatic verification.

**Comment by olivdb** [comment]
Thanks a lot @vbaranov, it's working now.

If useful for others, I forked `truffle-plugin-verify` to support Blockscout [here](https://github.com/olivdb/truffle-source-verify).

**Comment by vbaranov** [comment]
That is awesome, @olivdb! I am closing the issue then.
