### ISSUE TITLE
Endpoint 'transactions_csv' with 'address_id' parameter returns 504 error

### ISSUE THREAD

**Issue by Drunken-Dragon** [poanetwork/blockscout#3598]
Hi,
We use Blockscout in our app, with our own chain. One of our users tried to download the transactions for their wallet in CSV format, but it resulted in 504 error.

We tried to download the data in the same way in the browser - by clicking the “Download CSV” link that triggers a request sent to a path like this 
`<url>transactions_csv?address_id=<address>` 
and got the same result (an error page and also 504 status under "Network" tab in the web browser developers' console, for that request).

We also tried to fetch the data with curl directly from the blockscout container on our host, but it only resulted with "Empty reply from the server".

I also found that exactly the same issue can be reproduced on https://blockscout.com/poa/core.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
   Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
   Elixir 1.10.1 (compiled with Erlang/OTP 21)
* Operating System: 
   Ubuntu 18.04.4 LTS
* Blockscout Version/branch:
   v3.4.0-beta

### Steps to reproduce

- Go to https://blockscout.com/poa/core website, and select some address from the transactions list
- Try downloading the CSV data by clicking the 'CSV' link below the transactions list:
<img width="1224" alt="Screenshot 2021-02-01 at 15 01 18" src="https://user-images.githubusercontent.com/23655532/106468585-66f6e900-649e-11eb-986f-665182fdf5bd.png">
- Wait as the request is sent, for about dozen seconds (up to less than a minute) and the transaction list should be replaced with a Cloudflare 504 error page. The request is sent to url like below:

`https://blockscout.com/poa/core/transactions_csv?address_id=0xf1F51e933D6aAd056236E0a45c1cC5b335ca1A75`

### Expected behaviour

After sending request to 'transactions_csv' endpoint, via "Download CSV" link or some another tool, like curl, the transaction list for a given wallet address is downloaded in CSV format, instead of returning 504 error.

### Actual behaviour

Endpoint https://blockscout.com/poa/core/transactions_csv?address_id=0xf1F51e933D6aAd056236E0a45c1cC5b335ca1A75 returns 504 error.

**Comment by vbaranov** [comment]
Yes, CSV export currently doesn't support pagination or ability to specify data range. This is why it can hit 30 secs timeout if the address contains a huge number of transactions. You can use API endpoint to get the list of transactions.. It supports pagination.  For instance, in order to get first 1000 transactions related to address `0xf1F51e933D6aAd056236E0a45c1cC5b335ca1A75`, HTTP GET request URL would look like this:

https://blockscout.com/poa/core/api?module=account&action=txlist&address=0xf1F51e933D6aAd056236E0a45c1cC5b335ca1A75&page=1&offset=1000

or using cURL: `curl -X GET "https://blockscout.com/poa/core/api?module=account&action=txlist&address=0xf1F51e933D6aAd056236E0a45c1cC5b335ca1A75&page=1&offset=1000" -H "accept: application/json"`

**Comment by Drunken-Dragon** [comment]
Thanks for a swift response @vbaranov. We managed to get the data via curl, just like you presented.
