### ISSUE TITLE
Remove PhantomJS dependency

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/blockscout#403]
## Motivation
We should remove dependency on PhantomJS as it is no longer being actively maintained.

## Possible ideas
Puppeteer from Google Chrome team:
https://pptr.dev/
Tutorial link:
https://egghead.io/courses/end-to-end-testing-with-google-s-puppeteer-and-jest

Or another one to consider:
https://www.cypress.io/
Tutorial:
https://egghead.io/browse/tools/cypress

**Comment by tmecklem** [comment]
After updating Wallaby to use the experimental chromedriver support, the following error was dumped repeatedly to the console on macOS 10.13.6:

> chromedriver[97322:16183924] pid(97322)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!

It did not improve the test flakiness, so from a development environment perspective it's a net loss in terms of communicating test failures clearly. The error _appears_ to be spurious and was introduced in a recent version of macOS. Since this doesn't move anything forward at the moment, I'm putting this on the back burner again to address after higher priority work.

**Comment by StefanoDeVuono** [comment]
@tmecklem I'm experiencing the same issue on Mojave (moved from phantomjs to chromedriver on wallaby). Any insight into that error?
