### ISSUE TITLE
Contributor sees historical view of their account balance by block

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#433]
Very similar to an accounting application we should provide an updated history of an account balance. The backend for this issue was completed in #431.

This should probably be a separate tab and should include:
- [ ] mockup for this design
- [ ] graph of balances by date
- [ ] table with block, date, and balance

I'm open for any other suggestions on this topic.

**Comment by fvictorio** [comment]
Hi, @acravenho, I'll be working on this issue. Since I'm just learning Elixir/Phoenix, my plan is to open a PR with just a list of the historical balances, so that you can tell me if the approach I've taken is right. If it is, I will then add the graph and do the necessary changes to the table. Are you OK with this?

**Comment by acravenho** [comment]
@fvictorio Sounds good. You'll be working with the `address_coin_balances` tables. Please be aware that this table may exceed several billion records on Ethereum Mainnet. Your call to the DB is crucial so you may want to preload this or run async.
