### ISSUE TITLE
Switch to turn off live updates

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#579]
This is a feature request to add a switch in the header to toggle live updates off or on.  This will switch will toggle live events throughout the entire app and should save its state across pages. 

If the user turns live updates off on the homepage, navigating to the account page will keep the off state.

**Comment by jimmay5469** [comment]
I opened https://github.com/poanetwork/blockscout/issues/690 describing one of the problems this issue is trying to solve. If there are other problems this issue is trying to solve than please open more issues describing those problems.

If we look at those issues and the best option to solve them is adding a toggle to turn off live updates than we should do it. If the only issue is the one described in #690 there are much better ways to solve the problem than adding a toggle. If there are other problems it is trying to solve than likely we will have other good options to consider for those problems.

If we can avoid a toggle than I think it will provide a better user experience. For example, if the only issue is #690, than having live update turned on at all is a broken experience and we are leaving the user with 2 bad options:
1. turn off live updates and miss out on a great feature
2. leave live updates on and make it difficult to navigate the site
