### ISSUE TITLE
Address is  not recognized as contract

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/blockscout#602]
https://sokol-alpha.poaexplorer.com/en/addresses/0x54a7534b9fcc69c864e8de982d0fc54572b8e948/transactions

https://sokol-explorer.poa.network/account/0x54a7534b9fcc69c864e8de982d0fc54572b8e948

This  address is the contract address, however the explorer shows as regular address.

**Comment by acravenho** [comment]
@rstormsf 
## Overview
1. Realtime indexer missed block `4195774`
2. Realtime indexer sees block `4195775` and does not see the contract creation of [0x54a7534b9fcc69c864e8de982d0fc54572b8e948](https://sokol-alpha.poaexplorer.com/en/addresses/0x54a7534b9fcc69c864e8de982d0fc54572b8e948/transactions)
3. Transaction [0x5a3cc6615a258230408a1586ce55eacc4b657ac504b274b6d944ce4fbc638aba](https://sokol-alpha.poaexplorer.com/en/transactions/0x5a3cc6615a258230408a1586ce55eacc4b657ac504b274b6d944ce4fbc638aba/internal_transactions) is indexed by the realtime indexer at block `4195775`
4. Genesis indexer fills in the hole that was missed by the realtime indexer < 1m later but adds the internal transaction `create` to the end of its queue
<img width="1164" alt="screen shot 2018-08-25 at 1 45 08 am" src="https://user-images.githubusercontent.com/17620007/44615514-b2a30400-a809-11e8-8494-387090869faf.png"> (`internal_transactions_indexed_at` = NULL)

5. Because the Genesis indexer still has 3M transactions to index  [0x54a7534b9fcc69c864e8de982d0fc54572b8e948](https://sokol-alpha.poaexplorer.com/en/addresses/0x54a7534b9fcc69c864e8de982d0fc54572b8e948/transactions) does not look like a contract until tx [0x5a3cc6615a258230408a1586ce55eacc4b657ac504b274b6d944ce4fbc638aba](https://sokol-alpha.poaexplorer.com/en/transactions/0x5a3cc6615a258230408a1586ce55eacc4b657ac504b274b6d944ce4fbc638aba/internal_transactions) is processed.

## Conclusion
- This would not occur on a full index. If the realtime indexer misses a block/transaction the genesis indexer fills in the holes
- We now have a different realtime indexer that is subscription based that was merged Thursday evening (8/23).
- Our previous indexer was polling `block_time/2` and should not have missed it but it seems like a waste of time since that indexer is now retired.

I think it's worth our team to take a look at and maybe there is something that can be improved upon. I have downgraded this to medium until we know that our new indexer is having this same issue. I plan on deploying this new indexer this weekend to staging.

**Comment by igorffs** [comment]
I believe there is a possibility that we've been missing InternalTransactions and Balances "index requests" from our queue when we shut down the VM during deploy and development.

Both of these entities fetching process happen asynchronously (unbound from a BlockFetcher process transaction) using a GenServer to manage their queues that are not persisted. When the server stops the VM is turned off and this queue is lost. When it starts again, the Catchup BlockFecher will get the missing blocks that weren't indexed, but it won't check out the InternalTransactions from the Blocks that were indexed.

I'm not sure if that's exactly the scenario for the production environment, but it probably happens in development when we stop our servers. We should probably have some redundancy/persistence system for those async fetching the same way we have for the missing blocks.

@KronicDeth do you think there's a chance this hypothesis being related to this issue?

**Comment by acravenho** [comment]
@igorffs We have fields in the transactions table for `internal_transactions_indexed_at` which does not populate until the internal transaction for the parent transaction has been processed. 

I agree that we lose the state of catch-up internal transactions when we shutdown/redeploy (production) but from what I understand, the Genesis indexer will check this field at the end of its process and index these internal transactions when `internal_transaction_indexed_at = NULL`.

**Comment by igorffs** [comment]
That's right @acravenho, I didn't notice it. Both InternalTransactionFetcher and Balance already has this redundancy system that takes place right in the indexer initialization. 💪

**Comment by acravenho** [comment]
This has been resolved.
