### ISSUE TITLE
Instructions on how to run Blockscout with Ethereum mainnet

### ISSUE THREAD

**Issue by erosh1** [poanetwork/blockscout#603]
Add instructions on how to run with Ethereum network

**Comment by acravenho** [comment]
Thanks for the feedback @erosh1. We will be providing more detailed instructions on design, JSON RPC endpoints, and node specifications prior to our v1 release. 

Having these instructions will allow you to:
1. Add a css_variables stylesheet to update colors.
2. Know where to update the endpoints to run BlockScout on another EVM chain such as Ethereum Mainnet
3. We will provide specifications on exactly what options your node should have in order to work with BlockScout.

**Comment by erosh1** [comment]
can you provide a short memo on which files to change to get this running? I'd like to play with the explorer

**Comment by acravenho** [comment]
@erosh1 Is the explorer up and running on `sokol`? If so, please update the files `apps/indexer/config/dev/parity.exs` and `apps/explorer/config/dev/parity.exs`. You'll need to supply a full node with Websockets and tracing enabled.

**Comment by lehuwu** [comment]
@acravenho 
I succeeded in creating POA explorer, but I failed to try Ethereum mainnet.
Please  Add instructions on how to run with Ethereum network.
Thank you very much.

**Comment by igorbarinov** [comment]
Chain specific instructions can be found here https://forum.poa.network/c/blockscout/wiki
