### ISSUE TITLE
Indexer.TokenBalances.fetch_token_balances_from_blockchain message not found

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#692]
This error is happening every few seconds on Ethereum Mainnet

```
17:22:05.923 [error] Task #PID<0.15739.1> started from #PID<0.15736.1> terminating
** (KeyError) key :message not found in: %FunctionClauseError{args: nil, arity: 3, clauses: nil, function: :decode_abi_results, kind: nil, module: EthereumJSONRPC.Encoder}
    (explorer) lib/explorer/smart_contract/reader.ex:119: Explorer.SmartContract.Reader.query_contract/4
    (explorer) lib/explorer/token/balance_reader.ex:33: Explorer.Token.BalanceReader.get_balance_of/3
    (indexer) lib/indexer/token_balances.ex:40: Indexer.TokenBalances.fetch_token_balance/1
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<0.90668705/1 in Indexer.TokenBalances.fetch_token_balances_from_blockchain/1>, [%{address_hash: "0x336699d0d7eae8213bdc60661e336b703e5b7b21", block_number: 6264106, token_contract_address_hash: "0x602087badcb6ed10cc0dff3301b50d6f1993f3b3"}]]
```

### Environment

* Operating System: Linux

### Steps to reproduce

1. Index Ethereum Mainnet
2. View errors.log

### Expected behaviour

A token balance should be inserted in the db or ignored and checked later.

### Actual behaviour

Terminating fetcher.

**Comment by igorffs** [comment]
https://github.com/poanetwork/blockscout/blob/d106a2c2eeb72e01ae0696189bfaa42928f213e5/apps/explorer/lib/explorer/smart_contract/reader.ex#L114-L116

The `execute_contract_functions` function is returning an `{:error, {:bad_gateway, "url"}}` while querying a contract's function in our TokenBalanceFethcer and our `decode_abi_results` is naive and doesn't expect an error causing a match error:

https://github.com/poanetwork/blockscout/blob/d106a2c2eeb72e01ae0696189bfaa42928f213e5/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/encoder.ex#L71

We have to deal with an error possibility in this part of the code and we won't get these errors anymore. For the TokenBalanceFetcher this means that the fetching would occur and it would be retried due to our redundancy system.

But that would also make the problems in the network transparent. Would that be a concern @acravenho ?

**Comment by acravenho** [comment]
@igorffs Do you mean that it would show that something may be wrong with the node or that we would be showing the endpoint?

**Comment by igorffs** [comment]
> @igorffs Do you mean that it would show that something may be wrong with the node or that we would be showing the endpoint?

What I mean is that the network errors would continue to occur and we wouldn't know that they're happening. We could probably log these errors if they're valuable or just ignore them if we have a different tool to monitor the node and its responses.

**Comment by acravenho** [comment]
@phahulin Would you prefer us to ignore these Gateway timeouts for now or would you like us to log them? We're having an issue fetching token balances on Ethereum Mainnet. There is a very high number of tokens per block and when we attempt to fetch the balances, some of these requests are resulting in Gateway timeouts.

**Comment by phahulin** [comment]
No, let's not ignore errors
