### ISSUE TITLE
(KeyError) key :message not found in: %FunctionClauseError

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#800]
The exception handling code is throwing an exception:
```
** (KeyError) key :message not found in: %FunctionClauseError{args: nil, arity: 3, clauses: nil, function: :decode_results, kind: nil, module: Explorer.SmartContract.Reader}
    (explorer) lib/explorer/smart_contract/reader.ex:117: Explorer.SmartContract.Reader.query_contract/4
    (explorer) lib/explorer/token/balance_reader.ex:33: Explorer.Token.BalanceReader.get_balance_of/3
    (indexer) lib/indexer/token_balances.ex:42: Indexer.TokenBalances.fetch_token_balance/1
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<0.51900074/1 in Indexer.TokenBalances.fetch_token_balances_from_blockchain/1>, [%{address_hash: "0xd640358602c12115386be95e6d074a24b5a9acb1", block_number: 6612641, token_contract_address_hash: "0x590eb3599ca4305d8a64cbe24ef7d46c8f24bf1c"}]]
```
Luke: "It is assuming that `error`s from `rescue` always have a `message` key, which is not true, they do have to support the `message` function as a callback though as that is part of the protocol."

**Comment by Lucasnar** [comment]
I guess we just have to deal with errors that don't have the `:message` key, but I also think we should keep trying `error.message` if it is available (I think some errors from the `ex_abi` lib follow that and that's why it's here). As @KronicDeth said, we can get a message from any exception using [`Exception.message/1`](https://hexdocs.pm/elixir/Exception.html#message/1), and we could use that if it does not contain the `:message` key.
