### ISSUE TITLE
Investigate token count on the address page

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#948]
The token count on Blockscout is not matching the token counts on Etherscan. While I understand that the chain is still indexing, there are transactions with token transfers coming in but the token balances are not updating and showing them under the address's holdings. 

Here is an example:

https://blockscout.com/eth/mainnet/address/0x9a4a90e2732f3fa4087b0bb4bf85c76d14833df1/transactions

There are 10-20 transfers showing on blockscout coming into this address but the holdings are not reflecting these balances. 

1. We need to check that at some point these token balances will be fetched.
2. If failed, what system is in place to check them again?

**Comment by feliperenan** [comment]
I guess that the `TokenBalance.Fetcher` has a bottleneck. It is configured to fetch only 1 token balance at a time, but it receives a lot of token balances imported by catchup to be fetched. For instance:

* Catchup sends 1000 token balances to be fetched
* For each token balance, the `TokenBalance.Fetcher` is going to make a request to the smart contract to fetch the balance and import the new balance (one by one). It's not async since our `batch_size` is configured to be 1.
* Catchup sends more 1000 token balances to be fetched and the `TokenBalance.Fetcher` adds it to the queue.	

So, the `TokenBalance.Fetcher` will accumulate a lot of messages sent by catchup, it receives a lot by second, while is processing one by one. This way, the token balances will always be far behind the token transfers.

The possible solution would be increasing the `batch_size` and `init_chunk_size` to process more token balances at a time, then the token balances will be closer to the token transfers, although still behind. I remember that we decreased those numbers because we overloaded the node with a lot of requests, but I think we can increase it again and try to make it configurable to decrease when the indexer overload the node.

Answering the questions:
> 1. We need to check that at some point these token balances will be fetched.

It is going to be fetched, but it is taking too long.

> If failed, what system is in place to check them again?

If the import process fails, it will retry until everything is imported. If the `TokenBalance.Fetcher` crashes for any reason, when it startes, it will run a query to get all token balances that had not their values fetched to `TokenBalance.Fetcher` queue again. But if we get a timeout from the smart contract interaction, we don't update that token balance until the `TokenBalance.Fetcher` crashes. I think we need to create a mechanism to run that query periodically.

To wrap up, we need to do two things:
- Increase the `batch_size` and `init_chunk_size` to process more token balances in `TokenBalance.Fetcher`
- Run the query that finds token balances that weren't fetched periodically.

**Comment by acravenho** [comment]
@feliperenan Good investigation. I think we might need to bring @alexgaribay into the mix to see if what he's working on can help the node from timing out. If so, we can freely increase `batch_size` and let his work pause the indexer from sending any further requests when needed.
