### ISSUE TITLE
Improve Count of Wallet Addresses on Homepage

### ISSUE THREAD

**Issue by APshenkin** [poanetwork/blockscout#972]
Stange issue with wallets counter

In code https://github.com/poanetwork/blockscout/blob/702f701b3e6609be43711e15b88ac88f84ac4d59/apps/explorer/lib/explorer/chain.ex#L88

Request used with EXPLAIN (Why?). And for me it returns 2 rows in UI

```
EXPLAIN SELECT COUNT(a0.hash) FROM addresses AS a0 WHERE (a0.fetched_coin_balance > 0)

Finalize Aggregate  (cost=6762.09..6762.10 rows=1 width=8)
  ->  Gather  (cost=6761.88..6762.09 rows=2 width=8)
        Workers Planned: 2
        ->  Partial Aggregate  (cost=5761.88..5761.89 rows=1 width=8)
              ->  Parallel Seq Scan on addresses a0  (cost=0.00..5684.56 rows=30925 width=21)
                    Filter: (fetched_coin_balance > '0'::numeric)

```

But simple select return correct value

```
SELECT COUNT(a0.hash) FROM addresses AS a0 WHERE (a0.fetched_coin_balance > 0)

75249
```

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):

Erlang/OTP 21 [erts-10.1.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]
Elixir 1.7.3 (compiled with Erlang/OTP 21)

* Operating System:

Debian GNU/Linux 9 (stretch)

### Steps to reproduce

Just run syncing kovan (maybe any other network).

### Expected behaviour

Correct wallets counting

### Actual behaviour

After some time values are not correcspond actual values

**Comment by acravenho** [comment]
@APshenkin Thanks for reporting the issue. The reason this was put in place was due to it's speed. Using count queries in Postgres is painfully slow and causes pages to not load on larger chains. 

The `EXPLAIN` query was a quick fix but turns out to be horribly inaccurate. 

We are working on a better solution which should be released soon.

**Comment by amandasposito** [comment]
The wallet addresses count is being done [using the Explain Analyze command in order to improve performance](https://www.citusdata.com/blog/2016/10/12/count-performance?source=pg_weekly#dup_counts_estimated)

Even though the performance is good enough the result is highly inaccurate. The number can be seen at the [Home Page](https://blockscout.com/poa/core/) in the `Wallet addresses`, and in the [Accounts Page](https://blockscout.com/poa/core/accounts) in the `total addresses with a balance`.

**Acceptance Criteria**

* The `Wallet addresses` number must be closely accurate;
* The `total addresses with a balance` number must be closely accurate;
* The solution should take into consideration the performance in large chains, such as Ethereum Mainnet, and be careful with the number of addresses it will be handled.
